
name: student_dashboard
description: A student dashboard application.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.3
  animated_splash_screen: ^1.3.0
  lottie: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
flutter_icons:
  image_path: "assets/Icons/jay.png"
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/Inter-Regular.ttf
    - assets/fonts/Inter-Medium.ttf
    - assets/fonts/Inter-SemiBold.ttf
    - assets/fonts/Inter-Bold.ttf
    - assets/Icons/google_icons.png
    - assets/Icons/apple_icon.png
    - assets/anime/intro.json
    - assets/images/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
